from pathlib import Path
import json

ROOT = Path(__file__).resolve().parents[1]
CATALOG = ROOT / 'data' / 'catalog.json'
DOCS_OUT = ROOT / 'docs' / 'couriers.generated.js'
WORKER_OUT = ROOT / 'worker' / 'src' / 'couriers.generated.js'

data = json.loads(CATALOG.read_text(encoding='utf-8'))

frontend = (
    '// Generated by scripts/sync_couriers.py from data/catalog.json. Do not edit by hand.\n'
    f"window.MULLIMULLI_DISTANCE_FILTERS = {json.dumps(data['distanceTiers'], ensure_ascii=False, separators=(',', ':'))};\n"
    f"window.MULLIMULLI_COURIERS = {json.dumps(data['couriers'], ensure_ascii=False, separators=(',', ':'))};\n"
)
DOCS_OUT.write_text(frontend, encoding='utf-8')

worker_map = {
    c['id']: {
        'speed': c['speed'],
        'minHours': c.get('minHours', 0),
        'routeFactor': c.get('routeFactor', 1),
        'fail': c['fail'],
    }
    for c in data['couriers']
}
worker = (
    '// Generated by scripts/sync_couriers.py from data/catalog.json. Do not edit by hand.\n'
    f"export const COURIERS = {json.dumps(worker_map, ensure_ascii=False, separators=(',', ':'))};\n"
)
WORKER_OUT.write_text(worker, encoding='utf-8')
print(f'Synced {len(data["couriers"])} courier rules.')
